version: "3"

services:
  api:
    build:
      context: .
    container_name: fastify-docker-sequelize-api
    command: yarn start
    environment:
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
